### ISSUE TITLE
Weather problem

### ISSUE THREAD

**Issue by facutopa** [sw1ft-code/fitbit-versa-apfel#1]
Hi dev!

One problem, I'm from Buenos Aires, Argentina, the current weather is 12°C on Openweather web.
But on the clock, the weather say: "24°".
Do I must adjust the GPS manually for my current location?

Regards!

**Comment by facutopa** [comment]
You're right! Thanks for the help and sorry for this unnecessary issue :sweat:

**Comment by alansgilliam23** [comment]
Hey dev! Is there a way you can make this watch face for the Versa lite edition please??!! This is the best one I’ve seen and I would love this one
